[package]
name = "logparser"
version = "0.1.0"
authors = ["v0l"]

[dependencies]
regex = "0.2"
chrono = "0.4"
getopts = "0.2"
serde = "^1.0"
serde_json = "^1.0"
serde_derive = "^1.0"
maxminddb = "0.8.1"